#include "encoders.h"

/* Handles generated by CubeMX in main.c */
extern TIM_HandleTypeDef htim2;   /* encoder A: PA15 / PB3 */
extern TIM_HandleTypeDef htim3;   /* encoder B: PB4  / PB5 */

static int32_t  s_countA;
static int32_t  s_countB;
static int16_t  s_deltaA;
static int16_t  s_deltaB;

static uint16_t s_lastRawA;
static uint16_t s_lastRawB;

static uint32_t s_lastTick;
static uint32_t s_lastIntervalMs = ENCODER_SAMPLE_MS;

/* ------------------------------------------------------------------ */

void Encoders_Init(void)
{
    HAL_TIM_Encoder_Start(&htim2, TIM_CHANNEL_ALL);
    HAL_TIM_Encoder_Start(&htim3, TIM_CHANNEL_ALL);

    __HAL_TIM_SET_COUNTER(&htim2, 0);
    __HAL_TIM_SET_COUNTER(&htim3, 0);

    s_lastRawA = 0;
    s_lastRawB = 0;
    s_countA   = 0;
    s_countB   = 0;
    s_deltaA   = 0;
    s_deltaB   = 0;

    s_lastTick       = HAL_GetTick();
    s_lastIntervalMs = ENCODER_SAMPLE_MS;
}

void Encoders_Reset(void)
{
    /* Resync against the live counters rather than zeroing them, so a reset
     * landing mid-rotation cannot invent a spurious delta on the next call.
     * TIM2 is 32-bit on this part, so mask to 16 bits for consistency with
     * the delta arithmetic below. */
    s_lastRawA = (uint16_t)(__HAL_TIM_GET_COUNTER(&htim2) & 0xFFFFU);
    s_lastRawB = (uint16_t)(__HAL_TIM_GET_COUNTER(&htim3) & 0xFFFFU);
    s_countA   = 0;
    s_countB   = 0;
}

void Encoders_Update(void)
{
    uint32_t now = HAL_GetTick();
    uint32_t elapsed = now - s_lastTick;   /* wraps correctly at 49.7 days */

    uint16_t rawA;
    uint16_t rawB;
    int16_t  dA;
    int16_t  dB;

    if (elapsed < ENCODER_SAMPLE_MS)
    {
        return;
    }

    rawA = (uint16_t)(__HAL_TIM_GET_COUNTER(&htim2) & 0xFFFFU);
    rawB = (uint16_t)(__HAL_TIM_GET_COUNTER(&htim3) & 0xFFFFU);

    /* Unsigned 16-bit subtraction cast to signed handles wraparound in both
     * directions with no special case, provided the wheel moves less than
     * 32767 counts between samples. At 20 ms that is far beyond what a
     * gearmotor can physically do. */
    dA = (int16_t)(rawA - s_lastRawA);
    dB = (int16_t)(rawB - s_lastRawB);

    s_lastRawA = rawA;
    s_lastRawB = rawB;

#if ENCODER_A_INVERT
    dA = (int16_t)(-dA);
#endif
#if ENCODER_B_INVERT
    dB = (int16_t)(-dB);
#endif

    s_deltaA = dA;
    s_deltaB = dB;

    s_countA += (int32_t)dA;
    s_countB += (int32_t)dB;

    s_lastIntervalMs = elapsed;
    s_lastTick       = now;
}

/* ------------------------------------------------------------------ */

int32_t Encoder_A_GetCount(void) { return s_countA; }
int32_t Encoder_B_GetCount(void) { return s_countB; }

int16_t Encoder_A_GetDelta(void) { return s_deltaA; }
int16_t Encoder_B_GetDelta(void) { return s_deltaB; }

static int32_t rpm_from_delta(int16_t delta, uint32_t interval_ms)
{
    int32_t divisor;

    if (interval_ms == 0U)
    {
        return 0;
    }

    /* rpm = delta * 60000 / (COUNTS_PER_REV * interval_ms)
     * Worst case numerator 32767 * 60000 = 1.97e9, inside int32 range. */
    divisor = (int32_t)ENCODER_COUNTS_PER_REV * (int32_t)interval_ms;

    if (divisor == 0)
    {
        return 0;
    }

    return ((int32_t)delta * 60000) / divisor;
}

int32_t Encoder_A_GetRPM(void)
{
    return rpm_from_delta(s_deltaA, s_lastIntervalMs);
}

int32_t Encoder_B_GetRPM(void)
{
    return rpm_from_delta(s_deltaB, s_lastIntervalMs);
}
